name: Update Portfolio Prices

on:
  schedule:
    # Weekdays at 20:30 UTC (~4:30pm ET during DST) after US market close
    - cron: '30 20 * * 1-5'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pytz

      - name: Update data
        run: python update_data.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add portfolio.json
          git commit -m "Auto-update prices [skip ci]" || echo "Nothing to commit"
          git push
